    org     0
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    ld  (hl),A
    halt
    end